// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkOPfN2jYsmsBuqJVcLvkZ4xf1Qs9jBj8',
    appId: '1:764738911671:web:52e78cf67ca9c45d6cbc32',
    messagingSenderId: '764738911671',
    projectId: 'testpython-74a58',
    authDomain: 'testpython-74a58.firebaseapp.com',
    storageBucket: 'testpython-74a58.firebasestorage.app',
    measurementId: 'G-TQ2G8GWZ5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJPoaJHk_t4en96jyMr0sUB9Y2WT0kpek',
    appId: '1:764738911671:android:90b0f2a043f235886cbc32',
    messagingSenderId: '764738911671',
    projectId: 'testpython-74a58',
    storageBucket: 'testpython-74a58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG2N9DHNibXnhtJtYyGLwl-cYNM3c9aP0',
    appId: '1:764738911671:ios:88a6cf97bdba35c56cbc32',
    messagingSenderId: '764738911671',
    projectId: 'testpython-74a58',
    storageBucket: 'testpython-74a58.firebasestorage.app',
    iosBundleId: 'com.example.todoMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG2N9DHNibXnhtJtYyGLwl-cYNM3c9aP0',
    appId: '1:764738911671:ios:88a6cf97bdba35c56cbc32',
    messagingSenderId: '764738911671',
    projectId: 'testpython-74a58',
    storageBucket: 'testpython-74a58.firebasestorage.app',
    iosBundleId: 'com.example.todoMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkOPfN2jYsmsBuqJVcLvkZ4xf1Qs9jBj8',
    appId: '1:764738911671:web:92581bfc571eb0a56cbc32',
    messagingSenderId: '764738911671',
    projectId: 'testpython-74a58',
    authDomain: 'testpython-74a58.firebaseapp.com',
    storageBucket: 'testpython-74a58.firebasestorage.app',
    measurementId: 'G-9JFCR0BPW4',
  );
}
